version: "3.7"

services: 
  database_rentalx: 
    image: postgres
    container_name: database_rentalx
    restart: always
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentalx
    volumes: 
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentalx
    volumes: 
      - .:/usr/app
    network_mode: host

volumes: 
  pgdata:
    driver: local